const tr = {
    translation: {
        "editProfile": "Profili Düzenle",
        "userProfile": "Kullanıcı Profili",
        "logout": "Çıkış Yap",
        "saveChanges": "Your application succcessfully sent",
        "cancel": "İptal",
        "firstName": "Ad",
        "lastName": "Soyad",
        "email": "E-posta",
        "phoneNumber": "Telefon Numarası",
        "address": "Adres",
        "nationality": "Milliyet",
        "dateOfBirth": "Doğum Tarihi",
        "gender": "Cinsiyet",
        "male": "Erkek",
        "female": "Kadın",
        "other": "Diğer",
        "preferNotToSay": "Belirtmek istemiyorum",
        "selectGender": "Cinsiyet Seç",
        "notProvided": "Belirtilmemiş",
        "personalInformation": "Kişisel Bilgiler",
        "aboutMe": "Hakkımda",
        "noBiography": "Biyografi belirtilmemiş",
        "role": "Rol",
        "admin": "Yönetici",
        "user": "Kullanıcı",
        "memberSince": "Üyelik Başlangıcı",
        "unknown": "Bilinmiyor",
        "changePicture": "Resmi Değiştir",
        "loadingProfile": "Profil Yükleniyor",
        "updateProfileError": "Profil güncelleme hatası",
        "brandName": "KuvvatlyEyyam",
        "home": "Ana Sayfa",
        "university": "Üniversite",
        "services": "Hizmetler",
        "dashboard": "Admin Panel",
        "application": "Başvuru",
        "about": "Hakkında",
        "searchPlaceholder": "Ara...",
        "signIn": "Giriş Yap",
        "signUp": "Kaydol",
        //application form
        "uniqueId": "Benzersiz Kimlik (Pasaport/Vatandaşlık Kimliği)",
        "fatherName": "Babanın Adı",
        "motherName": "Annenin Adı",
        "chosenFaculty": "Seçilen Fakülte",
        "chosenField": "Seçilen Alan",
        "finishedSchool": "Bitirilen Okul",
        "contactInfo": "İletişim Bilgisi (Telefon/E-posta)",
        "applicationCountry": "Başvuru Yapılan Ülke",
        "uploadDocument": "Belge Yükle (PDF/Görsel)",
        "submitting": "Gönderiliyor...",
        "submitApplication": "Başvuruyu Gönder",
        "selectUniversity": "Bir üniversite seçin",
        "selectFaculty": "Bir fakülte seçin",
        "selectField": "Bir alan seçin",
        "enterField": "Çalışma alanınızı girin",
        "enterFieldManually": "Alanı manuel olarak girin"


    }
};

export default tr;