const ru = {
    translation: {
        "editProfile": "Редактировать профиль",
        "userProfile": "Профиль пользователя",
        "logout": "Выйти",
        "saveChanges": "Your application succcessfully sent",
        "cancel": "Отмена",
        "firstName": "Имя",
        "lastName": "Фамилия",
        "email": "Электронная почта",
        "phoneNumber": "Номер телефона",
        "address": "Адрес",
        "nationality": "Национальность",
        "dateOfBirth": "Дата рождения",
        "gender": "Пол",
        "male": "Мужской",
        "female": "Женский",
        "other": "Другое",
        "preferNotToSay": "Предпочитаю не указывать",
        "selectGender": "Выберите пол",
        "notProvided": "Не указано",
        "personalInformation": "Личная информация",
        "aboutMe": "Обо мне",
        "noBiography": "Биография не указана",
        "role": "Роль",
        "admin": "Администратор",
        "user": "Пользователь",
        "memberSince": "Участник с",
        "unknown": "Неизвестно",
        "changePicture": "Сменить фото",
        "loadingProfile": "Загрузка профиля",
        "updateProfileError": "Ошибка обновления профиля",
        "brandName": "КувватлыЭйям",
        "home": "Главная",
        "university": "Университет",
        "services": "Услуги",
        "dashboard": "Панель управления",
        "application": "Заявление",
        "about": "О нас",
        "searchPlaceholder": "Поиск...",
        "signIn": "Войти",
        "signUp": "Регистрация",
        // aplication form
        "uniqueId": "Уникальный идентификатор (Паспорт/ID гражданина)",
        "fatherName": "Имя отца",
        "motherName": "Имя матери",
        "chosenFaculty": "Выбранный факультет",
        "chosenField": "Выбранная специальность",
        "finishedSchool": "Оконченная школа",
        "contactInfo": "Контактная информация (Телефон/Email)",
        "applicationCountry": "Страна подачи заявления",
        "uploadDocument": "Загрузить документ (PDF/Изображение)",
        "submitting": "Отправка...",
        "submitApplication": "Подать заявку",
        "selectUniversity": "Выберите университет",
        "selectFaculty": "Выберите факультет",
        "selectField": "Выберите специальность",
        "enterField": "Введите вашу специальность",
        "enterFieldManually": "Введите специальность вручную"

    }
};

export default ru;